development:
  sessions:
    default:
      database: townent_development
      hosts:
        - localhost:27017
      options:
  options:
    preload_models: true
test:
  sessions:
    default:
      database: townent_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: townent
      hosts:
        - localhost:27017
      options:
  options:
    preload_models: true
